deployment:
  tasks:
    - export DEPLOYPATH=/home2/sinergiaverde/public_html/
    - /bin/mkdir -p $DEPLOYPATH
    - /usr/bin/rsync -av --delete --exclude ".htaccess" ./public/ $DEPLOYPATH
    - /bin/cp -f ./public/.htaccess $DEPLOYPATH 2>/dev/null || true
